### ISSUE TITLE
山形県の酒田、新庄の天気が取得できない

### ISSUE THREAD

**Issue by zakuni** [tsukumijima/weather-api#1]
地域ID [60030(酒田)](https://weather.tsukumijima.net/api/forecast/city/060030), [60040(新庄)](https://weather.tsukumijima.net/api/forecast/city/060040)について、`{"error":"The specified city ID does not exist."}`が返ってしまうようです

**Comment by tsukumijima** [comment]
まじすか…調べてみます。

**Comment by tsukumijima** [comment]
どうやら山形県と宮城県の ID が気象庁と livedoor 天気で逆らしく、[050030](https://weather.tsukumijima.net/api/forecast/city/050030) [050040](https://weather.tsukumijima.net/api/forecast/city/050040) なら見れました… 確認ミスです…
livedoor 天気側の正しい ID で見れるようにしておきます。

**Comment by zakuni** [comment]
ありがとうございます。本当にたまたま気づいたので、気づけて良かったです。

**Comment by tsukumijima** [comment]
https://github.com/tsukumijima/weather-api/commit/de538df43a43247588a7cbc1f7ee8acf52d8f7dc にて修正しました。
[060040(新庄)](https://weather.tsukumijima.net/api/forecast/city/060040) でちゃんと山形県（新庄）の天気が表示されていることが確認できるかと思います。

https://github.com/zakuni/weather-report にて使っていただけているみたいでありがたいです（もっとも、スクレイピングしている関係や天気予報のデータ自体が常に変わるのもあってまだ未知のバグがありそうですが……）。
報告していただけなければ気づかなかったと思います…、、 本当にありがとうございました！
