### ISSUE TITLE
【要望】chanceOfRainに新規プロパティ名を追加して欲しい

### ISSUE THREAD

**Issue by ghost** [tsukumijima/weather-api#2]
chanceOfRainの追加ありがとうございます。

■概要
Javaのクラスのフィールドと、本APIのプロパティ名をバインドして利用しようとしています。

Javaのフィールド名は数字から開始できないため、chanceOfRainの「00-06」についてバインド出来ない状況です。

■要望
chanceOfRainのプロパティ名について、

1. 数字から始まらない
2. ハイフンを使わない

など、Javaの変数名に利用可能な新規プロパティ名を用意して頂けると助かります。

例)
　T00_06
　T06_12

お忙しいところ恐縮ですが、ご検討下さいませ。

**Comment by tsukumijima** [comment]
![668](https://user-images.githubusercontent.com/39271166/100439745-43eb3a00-30e7-11eb-9a4d-7dfcf9cf037d.png)

> Javaのフィールド名は数字から開始できないため、chanceOfRainの「00-06」についてバインド出来ない状況です。

Java は触ったことがないのでなぜそのような事になるのか理解できていませんが（ JSON データを連想配列に格納して PHP なら `$weather['forecasts'][0]['chanceOfRain']['12-18']` という具合で必要なデータにアクセスすることを想定していました）、ひとまず画像のように新規プロパティを追加してみました。

API の方にも反映済みです。どうでしょうか？

**Comment by ghost** [comment]
無事Javaで取得する事が出来ました。
ありがとうございました。

**Comment by tsukumijima** [comment]
それはよかったですー！
要望ありがとうございました。
