### ISSUE TITLE
11/30に取得した明日、明後日の予報日が11/01、11/2になっている

### ISSUE THREAD

**Issue by ghost** [tsukumijima/weather-api#3]
■現象
　11/30 10:04頃、APIを叩きました。
　forecastsプロパティのdateについてですが、以下のようになっておりました。

　0番目の配列
　　date：2020-11-30
　　dateLabel：今日
　1番目の配列
　　date：2020-11-01　★2020-12-01ではない？
　　dateLabel：明日
　2番目の配列
　　date：2020-11-02　★2020-12-02ではない？
　　dateLabel：明後日

■質問
　明日、明後日が12月ではなく、11月になっております。
　仕様でしょうか？バグでしょうか？

**Comment by tsukumijima** [comment]
確認しましたがそうなってますね…
気象庁HPの日付に月の表記がないことから起こっているものと思われます。原因を調査中です。

**Comment by tsukumijima** [comment]
Commit e221832ae21e8e2fcdf51ba118626abc86b54c17 にて修正しました。
weather.tsukumijima.net の方も反映済みです。ご確認いただければと思います。

他にも何か不具合があれば報告していただけると幸いです（スクレイピングしているのと時間帯や日付によって予期しない入力データが入ったりするのでデバッグがなかなか大変…）

**Comment by ghost** [comment]
修正されている事を確認しました。
ありがとうございました。
