### ISSUE TITLE
帯広の天気が取得できない

### ISSUE THREAD

**Issue by hisuie08** [tsukumijima/weather-api#4]
表題のとおりです。
404を返して取得に失敗してしまいました。

**Comment by tsukumijima** [comment]
https://github.com/tsukumijima/weather-api/commit/5606ec9a06760fe3ca36f95d0ceefbf6561ce3c2 にて修正しました。
帯広と奄美は特殊で、原則都道府県 or 地方ごとに1つ設置されている地方気象台の下部施設、測候所にて観測が行われています。そのため、一地域であるにも関わらず気象庁 HP の内部で都道府県のような扱いになっていたのが原因です。こういうのやめてほしい…
https://weather.tsukumijima.net/api/forecast/city/014010 をご確認ください。修正できていると思います。
