### ISSUE TITLE
[要望] Content-Type を application/json にして欲しい

### ISSUE THREAD

**Issue by kanatech-west32** [tsukumijima/weather-api#5]
レスポンスヘッダーの Content-Type が text/html で出力されているようです。
application/json で出力していただくと FireFox などの JSON Viewer 内蔵のWebブラウザで
見やすくなります。
ご検討いただけますと幸甚です。

**Comment by tsukumijima** [comment]
ずっと application/json で出力されているものと思っていましたが、確かに text/html で出力されてしまっていますね…。
https://github.com/tsukumijima/weather-api/commit/e9b4ed522ce795baa9ff81a80609cadd91cc3f03 にて修正しました。要望いただけなければずっと気づかなかったでしょうし、とても助かりました。
ありがとうございました！

**Comment by kanatech-west32** [comment]
迅速なご対応ありがとうございます。
