### ISSUE TITLE
[要望] Content-Type に charset指定を含めて欲しい

### ISSUE THREAD

**Issue by kanatech-west32** [tsukumijima/weather-api#6]
レスポンスヘッダーの Content-Type に charset指定を含めていただけると
クライアント側で エンコード指定する手間が省けます。
ご検討いただけますと幸甚です。

**Comment by tsukumijima** [comment]
[こちら](https://qiita.com/niwasawa/items/030f0497446918a53324) の記事によると、仕様上は JSON は常に UTF-8 でエンコードされる必要があるため、charset の指定の必要はなく、むしろ冗長であるため非推奨だとあります。
他の API サービスでも JSON API のレスポンスに charset が指定されているケースはほとんどないようですし、charset  を指定する必要はないように思いますが、いかがでしょう。

**Comment by kanatech-west32** [comment]
ご回答ありがとうございます。
クライアント側のライブラリがcharsetを見てエンコードを決定してたため
上記のような要望となってしまいました。
Spring Framework で MediaType.APPLICATION_JSON_UTF8 が非推奨とされる根拠も理解できるのですが、
学習目的などで、JSONデータを単なる文字列として処理したい時などは (application/json を無視するため)
charsetがついていると都合の良い場面もあるかと思われます。
ただ、非指定が今後の主流になるということを考えるとクライアント側で対応する問題なのかもしれません。
開発者・運営者様のご判断に委ねます。

(追記)
クライアント側のライブラリとして利用したのは Android の Volleyでした。
StringRequest で取得すると charset 指定が無い時は デフォルト ISO-8859-1 でエンコードされるようです
（同ライブラリに Json～Request というのもあり、そちらで取得すると UTF-8 でエンコードしてくれるようです）

また、PowerShellでも試しました。
```
$web = Invoke-WebRequest "https://weather.tsukumijima.net/api/forecast/city/400040"
ConvertFrom-Json $web.Content
```
やはり デフォルトは ISO-8859-1 のようです。

WebAPIの本来の使用方法ではないかもしれませんが
charset指定が付いていると便利になる面もあるという事例まで。

**Comment by tsukumijima** [comment]
誤解されているかもしれないので一応説明しておくと、この API は Laravel 製で、Spring Framework との関係はありません。

ただ、仕様上は JSON のレスポンスヘッダーに charset を含めるべきではないようです。なぜなら、仕様上 JSON が UTF-8 以外のエンコードになることは考えられず冗長になる上に、そもそも仕様には存在しないためです。
とはいえブラウザ側がよしなに解釈してくれるせいで動作してしまうので、深く考えることなく使われているというのが現状のようです。調べてみると、GitHub API など、`charset=utf-8` を設定してくる API も多く存在するようでした。

> クライアント側のライブラリが charset を見てエンコードを決定してたため

クライアント側のライブラリが明示されていないのでわからないのですが、少なくとも明示的に指定がない場合は UTF-8 で読み込むライブラリが大半ではないでしょうか。
この API の文字コードが Shift-JIS になっているなら分かりますが、仕様に準拠して UTF-8 でレスポンスを返している以上、問題になるケースが思い当たりません。
仮に文字化けするとして、その際は明示的に読み込む文字エンコードを UTF-8 に指定すれば良いだけではないでしょうか。

--------

ところで、https://github.com/tsukumijima/weather-api/commit/e9b4ed522ce795baa9ff81a80609cadd91cc3f03 にあるように、この API で返すレスポンスは Laravel の \Illuminate\Http\JsonResponse です。コード側で明示的に `content-type: application/json` のヘッダーを付与しているわけではなく、Laravel 側で自動的に Response に応じた content-type が設定されています。

つまり、現在の `charset=utf-8` の指定がない状態は Laravel 側のデフォルトという事になります。他の API で charset=utf-8 が付与されているのも、単に内部で使われているフレームワークでそれがデフォルトになっているというだけの事でしょう。

この挙動を変更するには、HTTP ヘッダーを明示的に指定することで Laravel 側の挙動を上書きする必要があります。
しかし、前述の通り、本来は `application/json` だけを指定するのが正しいはずです。Laravel 側のデフォルトを上書きしてまで、仕様から逸れた状態にしたいとは思えません。
